# swram/test02/docker-stack.yaml
# swarm 에서는  stack 파일을 만들어 놓고 
# 배포할때는  docker stack deploy -c  <파일명> <stack명> 해서 배포를 한다  

networks:
  # my-net 이라는 이름의 network 를 만들겠다 
  my-net:
    # cluster 환경이기 때문에 overlay 로 설정 
    driver: overlay

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=172.16.8.203,rw,nfsvers=4
      device: ":/nfs/shared/zzz"

# docker-stack.yaml 을 실행하는 node 의 현재 경로에 있는 nginx.conf 파일을 
# 클라스터에 있는 모든 node 에서 실행하는 서비스(container)에서 사용할수 있도록 등록한다 
configs:
  nginx_config: # 이름은 마음대로 지을수 있다.
    file: ./nginx.conf

services:
  my-nginx:
    image: nginx:latest
    # host 의 80 port 연결은 container(nginx) 의 80 port 로 연결하겠다  
    ports:
      - '80:80'
    networks:
      - my-net
    deploy:
      replicas: 2
    # 미리 정의해서 설정한 nginx_config 를 사용하기 
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf
    # nginx 는 매우 가벼운 application
    # resources: 를 이용해서 cGroup 에서 제공하는 자원을 제한 혹은 최소량 확보를 할수가 있다.
    # 2core 는 2.0 개 만큼의 cpu 자원을 가지고 있다고 가정된다 
    resources:
      limits:
        cpu: '0.3' # 최대 0.3 코어 사용 허용
        memory: 256M # 최대 256MB RAM 허용
      reservations:
        cpus: '0.05' # 최소 0.05 코어를 보장한다
        memofy: 64M # 최소 64MB RAM 보장

  swarm-fastapi:
    image: myoli999/swarm-fastapi:1.1
    environment:
      # container 의 이름이 아닌 서비스의 이름이 db 접속 url 에 들어가는것을 유의한다 
      # postgresql://scott:tiger@<db서비스이름>:5432/scott_db
      - DB_URL=postgresql://scott:tiger@my-postgres:5432/scott_db
    # nginx 를 통해서 요청을 전달 받기 때문에 아래의 설정은 필요가 없다
    # ports:
    #   - '8000:8000'
    networks:
      - my-net
    deploy:
      replicas: 1
    resources:
      limits:
        cpus: '0.5' # 최대 0.5 코어 사용 허용
        memory: 512M # 최대 512MB RAM 허용
      reservations:
        cpus: '0.1' # 최소 0.1 코어 보장
        memory: 128M # 최소 128MB RAM 보장

  # db 서비스 
  my-postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: scott
      POSTGRES_PASSWORD: tiger
      POSTGRES_DB: scott_db
    volumes:
      # 미리 준비한 nfs volume 을 연결하고 
      - postgres_data:/varlib/postgresql/data
      # nfs 에 연결된 폴더의 파일을 bind mount 한다 
      # 처음 db 가 활성화 될때 최초 1번만 실행된다. 이미 사용하던 volume 이 있으면 실행안됨
      - /mnt/nfs/pg_init/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my-net
    deploy:
      # DB 는 replicas 1 개 
      replicas: 1
    resources:
      limits:
        cpus: '1.0' # 최대 1 코어 사용 허용
        memory: 1G  # 최대 1GB RAM 허용
      reservations:
        cpus: '0.25'  # 최소 0.25 코어 보장
        memory: 512M  # 최소 512MB RAM 보장
