# nginx 설정 파일  nginx.conf

# 동시접속 상한선 설정
events {
    worker_connections 1024;
}

http {

    # 다양한 종류의 파일을 정상 응답할수 있도록 (웹브라우저가 잘 해석할수 있도록)
    # 응답하는 파일이 어떤 종류의 파일인지에 대한 정보도 같이 응답 되도록 한다     
    include       /etc/nginx/mime.types;
    # 목록에 없는 파일은 다운로드 되도록 디폴트 설정 
    default_type  application/octet-stream;

    # 1. 트래픽을 보낼 목적지(Upstream) 정의
    upstream index_backend {
        server index-app:80;
    }
    upstream member_backend {
        server member-app:8000;
    }
    upstream post_backend {
        server post-app:8000;
    }

    # 2. 웹 서버 설정
    server {
        listen 80;
        server_name localhost;

        location / {
            # 위에서 정의한 upstream 그룹으로 트래픽을 토스!
            proxy_pass http://index_backend;
            
            # 클라이언트의 실제 IP와 호스트 정보를 백엔드에 그대로 전달해 줍니다.
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        location /members {
            # 위에서 정의한 upstream 그룹으로 트래픽을 토스!
            proxy_pass http://member_backend;
            
            # 클라이언트의 실제 IP와 호스트 정보를 백엔드에 그대로 전달해 줍니다.
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        location /posts {
            # 위에서 정의한 upstream 그룹으로 트래픽을 토스!
            proxy_pass http://post_backend;
            
            # 클라이언트의 실제 IP와 호스트 정보를 백엔드에 그대로 전달해 줍니다.
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}