---
- name: Setup Cloudflare Tunnel on AWS Ubuntu
  hosts: master
  become: yes

  tasks:
    - name: 1. 기존 서비스 정리
      command: cloudflared service uninstall
      failed_when: false

    - name: 2. Cloudflared 설치
      apt:
        deb: "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb"
        state: present
        update_cache: yes

    - name: 3. 터널 등록 및 실행
      command: "cloudflared service install {{ tunnel_token }}"